### PR TITLE
Fix Cmd+V and Cmd+C shortcuts

### LINKED ISSUE #34: Pasting inside xterm doesn't work

### PR DESCRIPTION
**Pull request by dragonDScript**
This fixes #34

**Known Issues**
This hasn't been tested since I don't own a Mac currently.

### CODE REVIEW

**Review by Ngomana — APPROVED** [review]

**Comment by martonlanga** [comment]
Thanks for this, but copy-pasting already worked (or did you have issues with it?) #34 is related to the xterm.js paste, which is not an electron related issue.

**Comment by dragonDScript** [comment]
This is for the app itself, not for xterm. If you have any text in your DOM, apart from xterm, in Mac you won't be able to copy it.

**Comment by martonlanga** [comment]
That works on Mac. This is only an issue with xterm

**Comment by dragonDScript** [comment]
> That works on Mac. This is only an issue with xterm

Are you sure? Have you tried to select text? A <p> element, for example

**Comment by martonlanga** [comment]
Yes. I think it's because Electron has a built-in Menu which includes Copy and Paste, and we are not overriding that.

**Comment by dragonDScript** [comment]
Ah, ok, that's fine.

**Pull request closed without merging**
