### PR TITLE
Added autoUpdater

### PR DESCRIPTION
**Pull request by dragonDScript**
In this PR, I have added:
- Auto Updates.
- Added contributors section in the README.md
- Fix an issue (see 0a2cd3d901f3c76985f87a316aef310012feaa3d) for other OS' compatibility (this will be my next PR).

**Known issues**
1. I have not tested this since I don't use OS X.
2. There is some debugging console.logs which must be removed.
3. ~~There is no way to trigger "Check for Updates" on the UI.~~  There is no way to trigger to check for updates from the UI, however there's an ipc event called "update".
4. You can't change the updater's settings visually.
5. Minor issues.

### CODE REVIEW

**Comment by martonlanga** [comment]
> macOS application must be signed in order for auto updating to work.

We'll need to have it signed first. Will merge it after that's done!

**Comment by dragonDScript** [comment]
Ok, that's fine! I'll start working on Linux support.

**Comment by martonlanga** [comment]
Linux might actually work without changing any of the Rust code since both os-es are unix based

**Comment by martonlanga** [comment]
Purchased an Apple Developer membership to get this started. Would also like to setup Github Actions right away to build for all the 3 platforms.

**Comment by dragonDScript** [comment]
> Purchased an Apple Developer membership to get this started. Would also like to setup Github Actions right away to build for all the 3 platforms.

I can make the GitHub Actions thing as well. It's simple to setup.

**Comment by martonlanga** [comment]
#43 is not required for auto updater, so we might do that later. Also it costs like $200+/y.

> I can make the GitHub Actions thing as well. It's simple to setup.

We need to wait for my Apple Dev membership license to get accepted. And also create actions to build Rust.

But you can get started with the cross platform electron actions part if you'd like.

**Comment by dragonDScript** [comment]
I have fixed somethings. Now, you can request to check for updates from an ipc event (`ipcRenderer.invoke("update")`). This must be implemented from the UI.
**Not tested**

**Pull request closed without merging**
